name: Setup
on: [push]

permissions: write-all

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # build names
      - name: Build names
        id: names
        run: |
          echo "repository=${REPOSITORY//$OWNER\//}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}

      # checkout
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # setup taskfile
      - uses: arduino/setup-task@v1

      # prepare files
      - name: Setup repository
        run: task setup
        env:
          REPOSITORY_NAME: ${{ steps.names.outputs.repository }}

      # commit changes
      - uses: peter-evans/create-pull-request@v8
        with:
          branch: feature/initialize
          title: 'chore: initialize repository'
          commit-message: 'chore: initialize repository from template'
          assignees: ${{ github.actor }}
          delete-branch: true
          signoff: true
